---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install python3 # noqa no-changed-when
      ansible.builtin.raw: test -e /usr/bin/python3 || ( apt update && apt install python3 -y )
      become: true
